Feature/lp74 out lined text field unit
irv205/droid_leaspert pull request #16
Opened 2023-04-04 16:03 UTC by AndresIvanMedinaH

**Task’s name**
OutlinedTextField - TextNumber

    **Task’s link to navigate to jira**
https://devaptivist.atlassian.net/browse/LP-74?atlOrigin=eyJpIjoiNjFjNjk5YmMwMjM4NDVkNThkYWE5MTcxOWNkOTI1MzQiLCJwIjoiaiJ9

    **General task’s description of what was added, deleted or updated in the code.**
As a developer, I must create a component like the image above

showing an OutlinedTextField, that implements a label in the top left corner and has the label text = unit

this TextField will only accept Int numbers

this TextField belongs to the screen Repair request

    **Attachment file of how looks your code in the app or in the preview if it is necessary**

![imagen](https://user-images.githubusercontent.com/128720218/229850766-33021b95-2740-44eb-a432-a0d6998184e1.png)

2023-04-04 19:05 UTC, IngKevel approved these changes

2023-04-05 15:58 UTC, juanislas77 commented on core/designsystem/src/main/java/com/iteneum/designsystem/components/OutLinedTextFieldMail.kt
> +                keyboardType = KeyboardType.Email // Especifica el teclado para el campo de texto como el de correo electrónico
Delete the comment, in the case you add a comment do it in english

2023-04-05 16:00 UTC, juanislas77 commented on core/designsystem/src/main/java/com/iteneum/designsystem/components/OutLinedTextFieldMail.kt
> +fun String.isValidEmail(): Boolean {
Delete and replace by a high order function

2023-04-05 16:01 UTC, juanislas77 commented on core/designsystem/src/main/java/com/iteneum/designsystem/components/OutlinedTextFieldUnit.kt
> +
Delete these empty lines

2023-04-05 16:02 UTC, juanislas77 commented on core/designsystem/src/main/java/com/iteneum/designsystem/components/OutLinedTextFieldMail.kt
> +}
Delete this extend function

2023-04-05 16:03 UTC, juanislas77 commented on core/designsystem/src/main/java/com/iteneum/designsystem/components/OutLinedTextFieldMail.kt
> +            },
Replace with a high order function

2023-04-05 16:03 UTC, juanislas77 commented on core/designsystem/src/main/java/com/iteneum/designsystem/components/OutlinedTextFieldUnit.kt
> +            },
Replace with a high order function

2023-04-05 16:05 UTC, juanislas77 requested changes
Resolve the comments

2023-04-05 22:00 UTC, juanislas77 approved these changes
Nice job

2023-04-05 22:11 UTC, merged